# get_customer_role()
# get_customer()
# print("city")
# get_city()
# get_city()
# get_city()
# get_city()
# print("route")
# get_route()
# get_route()
# get_route()
# print("voyage")
# get_voyage()
# print("voyage route")
# get_voyage_route()
# get_voyage_route()
# get_voyage_route()
# print("bus")
# get_bus()
# get_price()

from datetime import datetime

print(datetime.strptime("09-12-2022", '%d-%m-%Y').date())
